services:
  postgres:
    image: postgres:18-alpine
    container_name: market_mobility_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - market_mobility_pgdata:/var/lib/postgresql
    networks:
      - mm_net

  redis:
    image: redis:8-alpine
    container_name: market_mobility_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - mm_net

  app:
    build: .
    container_name: market_mobility_app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRY_MINUTES: ${JWT_ACCESS_EXPIRY_MINUTES}
      JWT_REFRESH_EXPIRY_DAYS: ${JWT_REFRESH_EXPIRY_DAYS}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - mm_net

volumes:
  market_mobility_pgdata:

networks:
  mm_net:
    driver: bridge
