spring:
  application:
    name: market-and-mobility
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false   # disables Redis repo scanning

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-to-be-changed-felix}
    access-expiry-minutes: ${JWT_ACCESS_EXPIRY_MINUTES:60}
    refresh-expiry-days: ${JWT_REFRESH_EXPIRY_DAYS:14}

springdoc:
  api-docs:
    enabled: true        # dev default
  swagger-ui:
    enabled: true        # dev default
